version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    # shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
  edge:
    image: selenium/node-edge:4.1.4-20220427
    # shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSIONS=1

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    # shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSIONS=1

  hub:
    image: selenium/hub:4.1.4-20220427
    container_name: hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  galaxy:
   image: butomo1989/docker-android-x86-8.1
   privileged: true
   depends_on:
     - hub
   ports:
     - "6080:6080"
   environment:
     - DEVICE=Samsung Galaxy S6
     - CONNECT_TO_GRID=True
     - APPIUM=true
     - SELENIUM_HOST=hub
     - MOBILE_WEB_TEST=False
     - AUTO_RECORD=True
  